### ISSUE TITLE
Can you specify the license

### ISSUE THREAD

**Issue by claytonrothschild** [tzole1155/ThreeDit#1]
Amazing work on the model and [sister repo](https://github.com/VCL3D/Pano3D). I have enjoyed using the tool and want to experiment building weights using my own dataset.

I noticed that Pano3D library is under MIT license and makes reference to the model code, but the model code is in this repository. This repository has no license. 

Do you mind clarifying the license?

Thank you 👍

**Comment by tzole1155** [comment]
Hi @claytonrothschild,

We are really glad that you've enjoyed using our project.

The model code itself is under MIT license, but the pre-trained models  are subject to the data terms specified in [Pano3D](https://vcl3d.github.io/Pano3D/download/)

Best,

Giorgos
