### ISSUE TITLE
Why isn't there this button?

### ISSUE THREAD

**Issue by XR720** [tzole1155/ThreeDit#5]
<img width="1370" alt="截屏2023-11-05 22 29 04" src="https://github.com/tzole1155/ThreeDit/assets/139452080/a9547756-22ea-4332-8dea-c1e91cc4227c">

**Comment by tzole1155** [comment]
Hello,

The reconstruction has been removed from the online app due to the limited provided resources.

However, you can still reconstruct the mesh from the point cloud.

Best,

Giorgos
